### ISSUE TITLE
Pretty Please Fix Pretty Print

### ISSUE THREAD

**Issue by Codrineye** [d0sboots/tower_json#1]
After the update, pretty print devolved into 
![image](https://github.com/d0sboots/tower_json/assets/87333825/1b8bcb6d-c7bb-4936-a74a-4e244256b82d)
where-as before it'd looked pretty
![image](https://github.com/d0sboots/tower_json/assets/87333825/fd3c9647-6030-48fb-a0a7-bfb758f4473f)

**Comment by Codrineye** [comment]
sorry for the big number, it's the image I could find

**Comment by d0sboots** [comment]
That's not my fault, that's because the format changed (although I'm surprised it changed like that). It used to be JSON, now it's apparently stringified JSON, which means that is the literal string that belongs in that field.
